"""add_bet_and_payout_transaction_types

Revision ID: 0ac723f05481
Revises: 267a79994ccc
Create Date: 2025-08-15 09:13:05.236080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac723f05481'
down_revision: Union[str, Sequence[str], None] = '267a79994ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE transactiontype ADD VALUE IF NOT EXISTS 'bet';")
    op.execute("ALTER TYPE transactiontype ADD VALUE IF NOT EXISTS 'payout';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
