"""expand_user_and_add_game_fairness_leaderboard_challenges_notifications

Revision ID: 267a79994ccc
Revises: dcd7ee2bd644
Create Date: 2025-08-15 08:05:13.547574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '267a79994ccc'
down_revision: Union[str, Sequence[str], None] = 'dcd7ee2bd644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

gamestatus = postgresql.ENUM('pending', 'completed', 'cancelled', name='gamestatus', create_type=False)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    gamestatus.create(op.get_bind(), checkfirst=True)
    op.create_table('challenges',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('challenge_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reward_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_table('game_seeds',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('server_seed', sa.String(length=64), nullable=False),
    sa.Column('server_seed_hash', sa.String(length=128), nullable=False),
    sa.Column('client_seed', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('nonce_counter', sa.Integer(), nullable=False),
    sa.Column('revealed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_seed_hash', name='uq_game_seeds_server_seed_hash')
    )
    op.create_index(op.f('ix_game_seeds_id'), 'game_seeds', ['id'], unique=False)
    op.create_table('games',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('target_number', sa.Integer(), nullable=False),
    sa.Column('result_number', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('win_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('house_edge', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('server_seed', sa.String(length=64), nullable=False),
    sa.Column('client_seed', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('game_hash', sa.String(length=128), nullable=False),
    sa.Column('status', gamestatus, nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_hash', name='uq_games_game_hash')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('leaderboard',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('total_wagered', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_won', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('games_count', sa.Integer(), nullable=False),
    sa.Column('biggest_win', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period_type', 'period_date', name='uq_leaderboard_user_period')
    )
    op.create_index(op.f('ix_leaderboard_id'), 'leaderboard', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('user_challenges',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('current_progress', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('reward_claimed', sa.Boolean(), nullable=False),
    sa.Column('date_started', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_user_challenges_user_challenge')
    )
    op.create_index(op.f('ix_user_challenges_id'), 'user_challenges', ['id'], unique=False)
    op.add_column('users', sa.Column('total_games_played', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('total_games_won', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('biggest_win', sa.Numeric(precision=18, scale=6), nullable=False))
    op.add_column('users', sa.Column('biggest_loss', sa.Numeric(precision=18, scale=6), nullable=False))
    op.add_column('users', sa.Column('first_bet_bonus_used', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    gamestatus.drop(op.get_bind(), checkfirst=False)
    op.drop_column('users', 'last_activity_at')
    op.drop_column('users', 'first_bet_bonus_used')
    op.drop_column('users', 'biggest_loss')
    op.drop_column('users', 'biggest_win')
    op.drop_column('users', 'total_games_won')
    op.drop_column('users', 'total_games_played')
    op.drop_index(op.f('ix_user_challenges_id'), table_name='user_challenges')
    op.drop_table('user_challenges')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_leaderboard_id'), table_name='leaderboard')
    op.drop_table('leaderboard')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_game_seeds_id'), table_name='game_seeds')
    op.drop_table('game_seeds')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
