"""add_bonus_transaction_and_user_first_deposit_flag

Revision ID: fe94eba4031b
Revises: 0ac723f05481
Create Date: 2025-08-15 10:36:09.463719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe94eba4031b'
down_revision: Union[str, Sequence[str], None] = '0ac723f05481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_deposit_bonus_used', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.execute("ALTER TYPE transactiontype ADD VALUE IF NOT EXISTS 'bonus'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_deposit_bonus_used')
    # ### end Alembic commands ###
